### ISSUE TITLE
Hide custom fields broken

### ISSUE THREAD

**Issue by pyroit** [ande3577/redmine_multi_column_custom_fields#13]
Hi thank you for this amazing plug in.

The custom field hide function for roles seems to be broken. So all fields are shown although they are set to hidden. 

I am working on it but up to now i just get "internal error" massages. 

System: 

Environment:
  Redmine version                2.6.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.0.1
  redmine_custom_workflow_email_support 0.0.1
  redmine_custom_workflows       0.0.4
  redmine_dashboard              2.3.3
  redmine_issue_history_filter   0.0.1
  redmine_monitoring_controlling 0.1.1
  redmine_multi_column_custom_fields 0.0.1
  sidebar_hide                   0.0.7

**Comment by ande3577** [comment]
Finally got a chance to look into this. Should be fixed in 9c7f70b1d2971ea61f7d34b03e066f98b47bd3cc
